// Compiled by ClojureScript 1.9.293 {}
goog.provide('pages.index');
goog.require('cljs.core');
goog.require('colours.ui_gradients');
goog.require('hoplon.core');
goog.require('hoplon.jquery');
goog.require('fonts.google_fonts');
goog.require('layouts.middle_right');
pages.index.gradient_name = "Day Tripper";
pages.index.gradient_stops = colours.ui_gradients.stops.call(null,pages.index.gradient_name);
hoplon.core.html.call(null,hoplon.core.head.call(null,hoplon.core.link.call(null,new cljs.core.Keyword(null,"href","href",-793805698),"https://necolas.github.io/normalize.css/latest/normalize.css",new cljs.core.Keyword(null,"rel","rel",1378823488),"stylesheet",new cljs.core.Keyword(null,"type","type",1174270348),"text/css"),fonts.google_fonts.fonts.call(null,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"name","name",1843675177),"Playfair Display",new cljs.core.Keyword(null,"fallback","fallback",761637929),"serif"], null),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"name","name",1843675177),"Raleway",new cljs.core.Keyword(null,"fallback","fallback",761637929),"sans-serif"], null)], null)),hoplon.core.link.call(null,new cljs.core.Keyword(null,"href","href",-793805698),"app.css",new cljs.core.Keyword(null,"rel","rel",1378823488),"stylesheet",new cljs.core.Keyword(null,"type","type",1174270348),"text/css")),hoplon.core.body.call(null,new cljs.core.Keyword(null,"css","css",1135045163),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"background","background",-863952629),[cljs.core.str("linear-gradient(to left, "),cljs.core.str(clojure.string.join.call(null,", ",pages.index.gradient_stops)),cljs.core.str(")")].join(''),new cljs.core.Keyword(null,"min-height","min-height",398480837),"100vh"], null),layouts.middle_right.middle_right.call(null,hoplon.core.div.call(null,new cljs.core.Keyword(null,"css","css",1135045163),cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"border-image-slice","border-image-slice",-4957056),new cljs.core.Keyword(null,"border-style","border-style",-485574304),new cljs.core.Keyword(null,"border-right","border-right",-668932860),new cljs.core.Keyword(null,"background-color","background-color",570434026),new cljs.core.Keyword(null,"border-image-source","border-image-source",1924962862),new cljs.core.Keyword(null,"background-clip","background-clip",1705503920),new cljs.core.Keyword(null,"border-image-repeat","border-image-repeat",-1007131119),new cljs.core.Keyword(null,"border-width","border-width",-1512605390),new cljs.core.Keyword(null,"padding","padding",1660304693),new cljs.core.Keyword(null,"border-color","border-color",-2059162761)],["33% 33%","dotted","none","white","url('border-dots.svg')","padding-box","round","4px","5vh 0 5vh 5vw",cljs.core.first.call(null,pages.index.gradient_stops)]),hoplon.core.h1.call(null,"Dim valley pty. ltd."),hoplon.core.p.call(null,"Lorem ipsum.")))));

//# sourceMappingURL=index.js.map