// Compiled by ClojureScript 1.9.293 {}
goog.provide('pages.milly');
goog.require('cljs.core');
goog.require('hoplon.core');
goog.require('layout.content_block');
pages.milly.content = (function pages$milly$content(){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [layout.content_block.content_inner.call(null,hoplon.core.div.call(null,new cljs.core.Keyword(null,"css","css",1135045163),cljs.core.merge.call(null,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"padding","padding",1660304693),"2.67rem 0"], null),fonts.hoplon.font_map__GT_css_map.call(null,fonts.config.playfair)),hoplon.core.h1.call(null,"Amelia Schmidt",new cljs.core.Keyword(null,"css","css",1135045163),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"margin","margin",-995903681),(0),new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"4rem"], null)),hoplon.core.span.call(null,"I believe the modern business consciously develops and evolves its unique model and way of doing business such that, over time, the needs of the business and customer quite naturally become one and the same.",new cljs.core.Keyword(null,"css","css",1135045163),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"1rem"], null)))),hoplon.core.img.call(null,new cljs.core.Keyword(null,"src","src",-1651076051),"https://pbs.twimg.com/media/C8DGQUCVYAABgc-.jpg:large",new cljs.core.Keyword(null,"css","css",1135045163),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"width","width",-384071477),"100%",new cljs.core.Keyword(null,"margin","margin",-995903681),"4px 0"], null)),layout.content_block.content_inner.call(null,hoplon.core.h2.call(null,"User experience research"),hoplon.core.ul.call(null,"I can provide the following UX services:",hoplon.core.li.call(null,"Design Sprint, Lean and Design Thinking workshops and planning facilitator"),hoplon.core.li.call(null,"User testing at all phases of the product lifecycle"),hoplon.core.li.call(null,"User interface prototyping and wireframing"),hoplon.core.li.call(null,"User experience research data synthesis")),hoplon.core.h2.call(null,"User interface engineering"),hoplon.core.ul.call(null,"I can provide the following front-end engineering services:",hoplon.core.li.call(null,"Advanced HTML/CSS implementations of preprocessors, frameworks, and other abstractions"),hoplon.core.li.call(null,"Custom JavaScript leveraging popular frameworks such as React, Angular, jQuery, etc."),hoplon.core.li.call(null,"Custom Clojure(Script) using the Hoplon UI framework (this site is built on Hoplon)")),hoplon.core.h2.call(null,"Modern business education"),hoplon.core.ul.call(null,"I can prepare and present educational courses on the following topics:",hoplon.core.li.call(null,"Agile project management"),hoplon.core.li.call(null,"Design thinking"),hoplon.core.li.call(null,"HTML, CSS and JavaScript"),hoplon.core.li.call(null,"Web computer science fundamentals")),hoplon.core.h2.call(null,"Public speaking, panel discussions, social change"),hoplon.core.p.call(null,"I am passionate about the next generation of coders being women."))], null);
});

//# sourceMappingURL=milly.js.map